# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dipnashu456
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: clickpe
# "service" is the name of this project. This will also be added to your AWS resource names.
service: user-authentication

custom:
  wsgi:
    app: app.app

  pythonRequirements:
    dockerizePip: true
    layer: true
    zip: true
    slim: true
    stripPackages:
      - pip
      - setuptools
      - wheel

provider:
  name: aws
  runtime: python3.13
  region: ap-south-1

  environment:
    # Application
    FLASK_APP: "app.py"
    FLASK_ENV: "development"
    SECRET_KEY: "this-is-strong-secret-key"

    # Database (hard-coded - local/dev style connection)
    DATABASE_URL: ${file(./secrets.json):DATABASE_URL}
    
    GOOGLE_CLIENT_ID: ${file(./secrets.json):GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${file(./secrets.json):GOOGLE_CLIENT_ID}
    
    GITHUB_CLIENT_ID: ${file(./secrets.json):GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${file(./secrets.json):GITHUB_CLIENT_SECRET}

    # Optional: JWT secret (re-using SECRET_KEY here)
    JWT_SECRET: "this-is-strong-secret-key"

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  api:
    handler: wsgi_handler.handler
    layers:
      - arn:aws:lambda:ap-south-1:829547187034:layer:user-authentication-dev-python-requirements:7
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - .venv/**
    - .serverless/**
    - node_modules/**
    - .gitignore
    - .git/**
    - __pycache__/**
    - .DS_Store
    - README.md
  individually: true

